spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    url: jdbc:mysql://localhost:3306/covidjavadb?serverTimezone=UTC
    username: root
    password: yyf1997213
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  mail:
    username: covidule@gmail.com
    host: smtp.gmail.com
    port: 587
    password: abcd1234?
    properties:
      mail:
        smtp:
          auth: true
          timeout: 3000
          writetimeout: 5000
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true